"""empty message

Revision ID: 71cd9b174c
Revises: 1b9c148a41d
Create Date: 2015-07-21 23:33:50.943253

"""

# revision identifiers, used by Alembic.
revision = '71cd9b174c'
down_revision = '1b9c148a41d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_password', new_column_name='password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', new_column_name='_password')
    ### end Alembic commands ###
